In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
# Load the Super Bowl data
sb_data = pd.read_csv("superbowl.csv")
sb_data.tail()

,Super Bowl,Coin Toss Outcome,Coin Toss Winner,Game Winner
50,51,Tails,Home Team,Away Team
51,52,Heads,Home Team,Away Team
52,53,Tails,Home Team,Away Team
53,54,Tails,Away Team,Home Team
54,55,Heads,Away Team,Home Team


In [3]:
# Generate sample data as a normal continuous random variable
#sample_data = stats.norm.rvs(loc=20, scale=2, size=50, random_state=5)

# Plot data as well as theoretical mean of 21
#fig, ax = plt.subplots()
#ax.hist(sample_data, alpha=0.5, label="Sample Data")
#ax.axvline(sample_data.mean(), linestyle="--", label=r"Sample Mean $\mu$")
#ax.axvline(21, linestyle="--", color="orange", label=r"Theoretical Mean $\mu_{0}$")
#ax.set_ylabel("Count")
#ax.legend();

In [4]:
sb_data["Coin Toss Winner"].value_counts()

Coin Toss Winner
Away Team    30
Home Team    25
Name: count, dtype: int64

In [5]:
sb_data["Game Winner"].value_counts()

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [6]:
coin_toss_counts = sb_data["Coin Toss Outcome"].value_counts()


In [7]:
fair_coin_expected = [sum(coin_toss_counts) / 2, sum(coin_toss_counts) / 2]
fair_coin_expected

[27.5, 27.5]

In [8]:
fair_coin_observed = coin_toss_counts.values
fair_coin_observed

array([29, 26])

In [9]:
fair_coin_result = stats.chisquare(fair_coin_observed, fair_coin_expected)
fair_coin_result

Power_divergenceResult(statistic=np.float64(0.16363636363636364), pvalue=np.float64(0.6858304344516056))

In [10]:
game_winner_counts = sb_data["Game Winner"].value_counts()
game_winner_counts

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [11]:
observe = game_winner_counts.values
observe

array([31, 24])

In [12]:
expected = [sum(game_winner_counts) / 2, sum(game_winner_counts) / 2]
expected

[27.5, 27.5]

In [13]:
results= stats.chisquare(observe, expected)
results

Power_divergenceResult(statistic=np.float64(0.8909090909090909), pvalue=np.float64(0.34523107177184))

In [14]:
nfl_games =  pd.read_csv(r"nfl_games.csv")
nfl_games.head()

,date,season,neutral,playoff,team1,team2,elo1,elo2,elo_prob1,score1,score2,result1
0,1920-09-26,1920,0,0,RII,STP,1503.947,1300.000,0.824651,48,0,1.0
1,1920-10-03,1920,0,0,AKR,WHE,1503.420,1300.000,0.824212,43,0,1.0
2,1920-10-03,1920,0,0,RCH,ABU,1503.420,1300.000,0.824212,10,0,1.0
3,1920-10-03,1920,0,0,DAY,COL,1493.002,1504.908,0.575819,14,0,1.0
4,1920-10-03,1920,0,0,RII,MUN,1516.108,1478.004,0.644171,45,0,1.0


In [15]:
# Data from FiveThirtyEight
nfl_data = pd.read_csv("nfl_games.csv")
# Narrow to relevant rows
nfl_data = nfl_data[(nfl_data["neutral"] == 0) & (nfl_data["playoff"] == 0) & (nfl_data["season"] >= 1966 )]
# Engineer a new feature
nfl_data.loc[nfl_data["result1"] == 0, "Game Winner"] = "Away Team"
nfl_data.loc[nfl_data["result1"] == 1, "Game Winner"] = "Home Team"

game_winner_counts_nfl = nfl_data["Game Winner"].value_counts().sort_index()
game_winner_counts_nfl

Game Winner
Away Team    5265
Home Team    7066
Name: count, dtype: int64

In [16]:
nfl_observed = game_winner_counts_nfl.values
nfl_observed

array([5265, 7066])

In [17]:
nfl_expected = [sum(nfl_observed) / 2, sum(nfl_observed) / 2]
nfl_expected

[np.float64(6165.5), np.float64(6165.5)]

In [18]:
nfl_chisquare = stats.chisquare(nfl_observed, nfl_expected)
nfl_chisquare

Power_divergenceResult(statistic=np.float64(263.0444408401589), pvalue=np.float64(3.723190824055013e-59))

In [19]:
independence_table = pd.crosstab(nfl_data["Game Winner"], nfl_data["season"])
independence_table

season,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Game Winner,,,,,,,,,,,,,,,,,,,,,
Away Team,68,75,94,68,72,74,87,66,82,81,...,110,108,101,107,117,106,108,99,120,128
Home Team,91,89,83,106,101,100,90,109,99,101,...,145,146,152,145,136,145,143,152,130,127


In [25]:
chi2,p,dof, exf=stats.chi2_contingency(independence_table)
print(chi2,p,dof,exf)

54.29369908874758 0.4631951063546661 54 [[ 67.88865461  70.02351796  75.57416268  74.29324467  73.866272
   74.29324467  75.57416268  74.72021734  77.28205336  77.70902603
   83.25967075  83.68664342  95.21490552  95.64187819  95.21490552
   95.21490552  53.37158381  95.21490552  95.21490552  95.64187819
   94.78793285  89.23728814  95.21490552  95.21490552  95.64187819
   95.64187819  95.64187819  95.64187819  95.64187819 102.47344092
  102.47344092 101.61949558 102.47344092 105.88922229 105.88922229
  105.88922229 108.87803098 108.87803098 109.30500365 107.59711297
  109.30500365 108.87803098 108.45105831 108.87803098 108.45105831
  108.87803098 108.45105831 108.02408564 107.59711297 108.02408564
  107.1701403  107.1701403  107.1701403  106.74316763 108.87803098]
 [ 91.11134539  93.97648204 101.42583732  99.70675533  99.133728
   99.70675533 101.42583732 100.27978266 103.71794664 104.29097397
  111.74032925 112.31335658 127.78509448 128.35812181 127.78509448
  127.78509448  71.628416